# Generated by Django 3.2 on 2021-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='maxcyl',
            new_name='maximum_delivery_distance',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='maxdist',
        ),
        migrations.AddField(
            model_name='listing',
            name='maximum_cylinders',
            field=models.IntegerField(default=1),
        ),
    ]
