# Generated by Django 3.2 on 2021-04-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0002_auto_20210423_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='maximum_cylinders',
            new_name='cylinders_available',
        ),
    ]
