# Generated by Django 3.2 on 2021-04-24 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0003_rename_maximum_cylinders_listing_cylinders_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='listing',
            name='address_line_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pincode',
            field=models.IntegerField(default=700000),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
