# Generated by Django 3.1.7 on 2021-04-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0004_auto_20210424_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='maximum_delivery_distance',
            field=models.IntegerField(default=1),
        ),
    ]
