# Generated by Django 3.1.7 on 2021-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0008_auto_20210425_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cylinders_per_customer',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
