# Generated by Django 3.2 on 2021-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0011_auto_20210426_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='verified_on',
            field=models.TimeField(),
        ),
    ]
