# Generated by Django 3.2 on 2021-04-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_co_away', '0012_alter_listing_verified_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-verified_on',)},
        ),
    ]
